# Generated by Django 4.2.9 on 2024-05-07 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookdata',
            old_name='publisher',
            new_name='publish',
        ),
    ]
