# Generated by Django 4.2.9 on 2024-05-07 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_rename_publisher_bookdata_publish'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookdata',
            old_name='publisher_date',
            new_name='publish_date',
        ),
        migrations.RenameField(
            model_name='bookdata',
            old_name='publish',
            new_name='publisher',
        ),
    ]
