# Generated by Django 4.2.9 on 2024-05-21 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_rename_publisher_date_bookdata_publish_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booklendrecord',
            old_name='borrow',
            new_name='borrower',
        ),
    ]
