# Generated by Django 4.2.9 on 2024-05-21 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('M', '男性'), ('F', '女性')], max_length=1, null=True),
        ),
    ]
