# Generated by Django 4.2.9 on 2024-05-21 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_student_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('男', 'M'), ('女', 'F')], max_length=1, null=True),
        ),
    ]
